output: main.o Assignment.o LibraryAssignment.o Book.o Library.o
	g++ main.o Assignment.o LibraryAssignment.o Book.o Library.o -o output
	rm -f *.o

main.o:
	g++ -c main.cpp

Assignment.o:
	g++ -c Assignment.cpp
	
LibraryAssignment.o:
	g++ -c LibraryAssignment.cpp
	
Book.o:
	g++ -c Book.cpp
	
Library.o:
	g++ -c Library.cpp

